version: "3"

services:
  dev-mhcseqnet2:
    image: dev-mhcseqnet2:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    runtime: nvidia
    ipc: host
    network_mode: "host"
    user: "0:0" # run as root
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      # This option is needed only when you wish to use GUI
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      # I choose to mount the folder containing this repository.
      - type: bind
        source: /media/zen3515/Data/Zenthesis
        target: /media/zen3515/Data/Zenthesis
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    # command: tail -f /dev/null
    command: "-f /dev/null"
    entrypoint: /usr/bin/tail
    tty: true

